#!/bin/sh

if [ -f "./environ" ]; then
    . ./environ
fi

set -e

if [ -n "$GORP_MYSQL_DSN" ]; then
    export GORP_TEST_DSN="$GORP_MYSQL_DSN"
    export GORP_TEST_DIALECT="mysql"
    go test
else
    echo "Skipping MySQL, \$GORP_MYSQL_DSN=$GORP_MYSQL_DSN"
    if [ -n "$GORP_FAIL_ON_SKIP" ]; then
        exit -1
    fi
fi

if [ -n "$GORP_POSTGRES_DSN" ]; then
    export GORP_TEST_DSN="$GORP_POSTGRES_DSN"
    export GORP_TEST_DIALECT="postgres"
    go test
else
    echo "Skipping PostgreSQL, \$GORP_POSTGRES_DSN=$GORP_POSTGRES_DSN"
    if [ -n "$GORP_FAIL_ON_SKIP" ]; then
        exit -1
    fi
fi

if [ -n "$GORP_SQLITE_DSN" ]; then
    export GORP_TEST_DSN="$GORP_SQLITE_DSN"
    export GORP_TEST_DIALECT="sqlite"
    go test
else
    echo "Skipping SQLite, \$GORP_SQLITE_DSN=$GORP_SQLITE_DSN"
    if [ -n "$GORP_FAIL_ON_SKIP" ]; then
        exit -1
    fi
fi

