#!/bin/sh
#
# To use this script, set the following environment variables:
#
#   GORP_MYSQL_DSN - mysql connect DSN, like "gorptest/gorptest/gorptest"
#   GORP_POSTGRES_DSN - postgres connect DSN, eg:
#        "username=gorptest password=gorptest dbname=gorptest ssl-mode=disable"
#   GORP_SQLITE_DSN - sqlite connect DSN, which is a path to a sqlite file.
#   GORP_FAIL_ON_SKIP - optional, will fail if any DBs are skipped (for CI, mostly)
#
# In addition to this, you can create an `environ` file in this directory which
# will be sourced and ignored by git.
#


if [ -f "./environ" ]; then
    . ./environ
fi

set -e

if [ -n "$GORP_MYSQL_DSN" ]; then
    export GORP_TEST_DSN="$GORP_MYSQL_DSN"
    export GORP_TEST_DIALECT="mysql"
    go test
else
    echo "Skipping MySQL, \$GORP_MYSQL_DSN=$GORP_MYSQL_DSN"
    if [ -n "$GORP_FAIL_ON_SKIP" ]; then
        exit -1
    fi
fi

if [ -n "$GORP_POSTGRES_DSN" ]; then
    export GORP_TEST_DSN="$GORP_POSTGRES_DSN"
    export GORP_TEST_DIALECT="postgres"
    go test
else
    echo "Skipping PostgreSQL, \$GORP_POSTGRES_DSN=$GORP_POSTGRES_DSN"
    if [ -n "$GORP_FAIL_ON_SKIP" ]; then
        exit -1
    fi
fi

if [ -n "$GORP_SQLITE_DSN" ]; then
    export GORP_TEST_DSN="$GORP_SQLITE_DSN"
    export GORP_TEST_DIALECT="sqlite"
    go test
else
    echo "Skipping SQLite, \$GORP_SQLITE_DSN=$GORP_SQLITE_DSN"
    if [ -n "$GORP_FAIL_ON_SKIP" ]; then
        exit -1
    fi
fi

